version: '3.7'

services:

  keycloak-postgres:
      image: postgres:12.4
      container_name: keycloak-postgres-container
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      networks:
        - keycloak_network

  keycloak:
      image: jboss/keycloak:12.0.1
      container_name: keycloak-container
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: keycloak-postgres-container
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: password
      ports:
        - 18080:8080
      depends_on:
        - keycloak-postgres
      networks:
        - keycloak_network

networks:
  keycloak_network:
    driver: bridge

